apiVersion: v1
kind: Service
metadata:
  name: ml-platform-gateway
  namespace: ml-platform
spec:
  type: NodePort
  selector:
    app: ml-platform-gateway
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
